# Generated by Django 3.1.1 on 2021-01-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.CharField(max_length=255)),
                ('ultimate', models.IntegerField()),
                ('descriptions', models.CharField(max_length=1024)),
                ('image_url', models.CharField(max_length=512)),
            ],
        ),
    ]
