# Generated by Django 3.1.1 on 2021-06-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(default='NA', editable=False, max_length=1024)),
                ('q2', models.CharField(default='NA', editable=False, max_length=1024)),
                ('q3', models.CharField(default='NA', editable=False, max_length=1024)),
                ('q4', models.CharField(default='NA', editable=False, max_length=1024)),
                ('q5', models.CharField(default='NA', editable=False, max_length=1024)),
                ('q6', models.CharField(default='NA', editable=False, max_length=1024)),
            ],
        ),
    ]
