# Generated by Django 3.1.1 on 2021-06-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomuser',
            name='question_cnt',
            field=models.IntegerField(default=99),
            preserve_default=False,
        ),
    ]
