# Generated by Django 3.1.1 on 2021-06-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_randomuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conseil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20000)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='q_to_skip',
            field=models.CharField(default='', editable=False, max_length=1024),
        ),
        migrations.AlterField(
            model_name='randomuser',
            name='q1',
            field=models.CharField(default='Ask', editable=False, max_length=1024),
        ),
        migrations.AlterField(
            model_name='randomuser',
            name='q2',
            field=models.CharField(default='Ask', editable=False, max_length=1024),
        ),
        migrations.AlterField(
            model_name='randomuser',
            name='q3',
            field=models.CharField(default='Ask', editable=False, max_length=1024),
        ),
        migrations.AlterField(
            model_name='randomuser',
            name='q4',
            field=models.CharField(default='Ask', editable=False, max_length=1024),
        ),
        migrations.AlterField(
            model_name='randomuser',
            name='q5',
            field=models.CharField(default='Ask', editable=False, max_length=1024),
        ),
        migrations.AlterField(
            model_name='randomuser',
            name='q6',
            field=models.CharField(default='Ask', editable=False, max_length=1024),
        ),
    ]
