# Generated by Django 3.1.1 on 2021-06-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_randomuser_question_cnt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='q_to_skip',
            new_name='q_to_ask',
        ),
        migrations.AlterField(
            model_name='randomuser',
            name='q2',
            field=models.CharField(default='skip', editable=False, max_length=1024),
        ),
        migrations.AlterField(
            model_name='randomuser',
            name='q3',
            field=models.CharField(default='skip', editable=False, max_length=1024),
        ),
        migrations.AlterField(
            model_name='randomuser',
            name='q4',
            field=models.CharField(default='skip', editable=False, max_length=1024),
        ),
        migrations.AlterField(
            model_name='randomuser',
            name='q5',
            field=models.CharField(default='skip', editable=False, max_length=1024),
        ),
        migrations.AlterField(
            model_name='randomuser',
            name='q6',
            field=models.CharField(default='skip', editable=False, max_length=1024),
        ),
    ]
