# Generated by Django 3.1.1 on 2021-06-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_randomuser_question_cnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomuser',
            name='question_cnt',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
