# Generated by Django 3.1.1 on 2021-06-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210605_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conseil',
            name='text',
        ),
        migrations.AddField(
            model_name='conseil',
            name='Q1',
            field=models.CharField(default='<any>', editable=False, max_length=1024),
        ),
        migrations.AddField(
            model_name='conseil',
            name='Q2',
            field=models.CharField(default='<any>', editable=False, max_length=1024),
        ),
        migrations.AddField(
            model_name='conseil',
            name='Q3',
            field=models.CharField(default='<any>', editable=False, max_length=1024),
        ),
        migrations.AddField(
            model_name='conseil',
            name='Q4',
            field=models.CharField(default='<any>', editable=False, max_length=1024),
        ),
        migrations.AddField(
            model_name='conseil',
            name='Q5',
            field=models.CharField(default='<any>', editable=False, max_length=1024),
        ),
        migrations.AddField(
            model_name='conseil',
            name='ctext',
            field=models.CharField(default='this is a dummy advice', max_length=1024),
            preserve_default=False,
        ),
    ]
