# Generated by Django 3.1.1 on 2021-06-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210605_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conseil',
            old_name='Q1',
            new_name='q1',
        ),
        migrations.RenameField(
            model_name='conseil',
            old_name='Q2',
            new_name='q2',
        ),
        migrations.RenameField(
            model_name='conseil',
            old_name='Q3',
            new_name='q3',
        ),
        migrations.RenameField(
            model_name='conseil',
            old_name='Q4',
            new_name='q4',
        ),
        migrations.RenameField(
            model_name='conseil',
            old_name='Q5',
            new_name='q5',
        ),
        migrations.AddField(
            model_name='conseil',
            name='q6',
            field=models.CharField(default='<any>', editable=False, max_length=1024),
        ),
    ]
