# Generated by Django 3.1.1 on 2021-06-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210605_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='anumber',
            field=models.CharField(max_length=1024),
        ),
    ]
